version: '3.7'

services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - my_app
    networks:
      - front-network
  my_app:
    build:
      context: .
      dockerfile: single-stage.dockerfile
    ports:
      - '3000'
    deploy :
      replicas: 4
    restart: always
    environment:
      - PING_LISTEN_PORT=3000
    networks:
      - front-network
  
networks:
  front-network:
    driver: bridge
